# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yousuf Sohail
email: hi@yousufsohail.com
description: >-
  Engineering Manager and product engineer with 13+ years building mobile apps at scale.
  Writing about Android, Kotlin, KMM, team leadership, and things that matter.
baseurl: ""
url: "https://yousufsohail.github.io"
twitter_username: _yousufsohail
github_username: yousufsohail

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: Yousuf Sohail
lang: en_US

# Social media profiles
social:
  name: Yousuf Sohail
  links:
    - https://twitter.com/_yousufsohail
    - https://github.com/yousufsohail
    - https://linkedin.com/in/yousufsohail
